BEGIN;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TABLE libraries (
    library_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    city TEXT,
    state TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT libraries_code_not_blank CHECK (BTRIM(code) <> ''),
    CONSTRAINT libraries_name_not_blank CHECK (BTRIM(name) <> '')
);

CREATE UNIQUE INDEX libraries_code_lower_uidx
    ON libraries ((LOWER(code)));

CREATE UNIQUE INDEX libraries_name_lower_uidx
    ON libraries ((LOWER(name)));

CREATE TABLE library_aliases (
    alias_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    library_id BIGINT NOT NULL REFERENCES libraries(library_id) ON DELETE CASCADE,
    alias TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT library_aliases_alias_not_blank CHECK (BTRIM(alias) <> '')
);

CREATE UNIQUE INDEX library_aliases_lower_alias_uidx
    ON library_aliases ((LOWER(alias)));

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role TEXT NOT NULL,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    legacy_source TEXT,
    legacy_source_id BIGINT,
    managed_library_id BIGINT REFERENCES libraries(library_id) ON DELETE SET NULL,
    email_verified_at TIMESTAMPTZ,
    must_reset_password BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT users_role_check CHECK (role IN ('member', 'admin', 'developer')),
    CONSTRAINT users_name_not_blank CHECK (BTRIM(full_name) <> ''),
    CONSTRAINT users_email_not_blank CHECK (BTRIM(email) <> ''),
    CONSTRAINT users_password_hash_not_blank CHECK (BTRIM(password_hash) <> ''),
    CONSTRAINT users_legacy_pair_check CHECK (
        (legacy_source IS NULL AND legacy_source_id IS NULL)
        OR (legacy_source IS NOT NULL AND legacy_source_id IS NOT NULL)
    ),
    CONSTRAINT users_admin_library_check CHECK (
        (role = 'member' AND managed_library_id IS NULL)
        OR (role = 'admin' AND managed_library_id IS NOT NULL)
        OR (role = 'developer' AND managed_library_id IS NULL)
    )
);

CREATE UNIQUE INDEX users_email_lower_uidx
    ON users ((LOWER(email)));

CREATE INDEX users_role_idx
    ON users (role);

CREATE UNIQUE INDEX users_legacy_source_uidx
    ON users (legacy_source, legacy_source_id)
    WHERE legacy_source IS NOT NULL AND legacy_source_id IS NOT NULL;

CREATE INDEX users_managed_library_idx
    ON users (managed_library_id)
    WHERE managed_library_id IS NOT NULL;

CREATE TABLE books (
    book_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    library_id BIGINT NOT NULL REFERENCES libraries(library_id) ON DELETE RESTRICT,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    isbn TEXT,
    read_online_url TEXT,
    total_copies INTEGER NOT NULL,
    issue_total_copies INTEGER NOT NULL,
    available_copies INTEGER NOT NULL,
    slot_booking_copies INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT books_title_not_blank CHECK (BTRIM(title) <> ''),
    CONSTRAINT books_author_not_blank CHECK (BTRIM(author) <> ''),
    CONSTRAINT books_total_copies_check CHECK (total_copies >= 0),
    CONSTRAINT books_issue_total_copies_check CHECK (
        issue_total_copies >= 0
        AND issue_total_copies <= total_copies
    ),
    CONSTRAINT books_available_copies_check CHECK (
        available_copies >= 0
        AND available_copies <= issue_total_copies
    ),
    CONSTRAINT books_slot_booking_copies_check CHECK (
        slot_booking_copies >= 0
        AND slot_booking_copies <= total_copies
    )
);

CREATE INDEX books_library_idx
    ON books (library_id);

CREATE INDEX books_title_lower_idx
    ON books ((LOWER(title)));

CREATE INDEX books_author_lower_idx
    ON books ((LOWER(author)));

CREATE TABLE borrow_requests (
    borrow_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    book_id BIGINT NOT NULL REFERENCES books(book_id) ON DELETE RESTRICT,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status TEXT NOT NULL DEFAULT 'pending',
    reviewed_at TIMESTAMPTZ,
    reviewed_by_user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    rejection_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT borrow_requests_status_check CHECK (
        status IN ('pending', 'approved', 'rejected', 'cancelled')
    ),
    CONSTRAINT borrow_requests_review_fields_check CHECK (
        (status = 'pending' AND reviewed_at IS NULL AND reviewed_by_user_id IS NULL AND rejection_reason IS NULL)
        OR (status <> 'pending' AND reviewed_at IS NOT NULL)
    ),
    CONSTRAINT borrow_requests_rejection_reason_check CHECK (
        (status = 'rejected' AND rejection_reason IS NOT NULL)
        OR status <> 'rejected'
    )
);

CREATE UNIQUE INDEX borrow_requests_one_pending_per_member_book_uidx
    ON borrow_requests (member_id, book_id)
    WHERE status = 'pending';

CREATE INDEX borrow_requests_book_status_idx
    ON borrow_requests (book_id, status, requested_at DESC);

CREATE INDEX borrow_requests_member_idx
    ON borrow_requests (member_id, requested_at DESC);

CREATE TABLE book_loans (
    loan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    borrow_request_id BIGINT UNIQUE REFERENCES borrow_requests(borrow_request_id) ON DELETE SET NULL,
    member_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    book_id BIGINT NOT NULL REFERENCES books(book_id) ON DELETE RESTRICT,
    issued_by_user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    due_at TIMESTAMPTZ NOT NULL,
    returned_at TIMESTAMPTZ,
    fine_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT book_loans_due_after_issue_check CHECK (due_at > issued_at),
    CONSTRAINT book_loans_return_after_issue_check CHECK (
        returned_at IS NULL OR returned_at >= issued_at
    ),
    CONSTRAINT book_loans_fine_amount_check CHECK (fine_amount >= 0)
);

CREATE UNIQUE INDEX book_loans_one_active_per_member_book_uidx
    ON book_loans (member_id, book_id)
    WHERE returned_at IS NULL;

CREATE INDEX book_loans_active_book_idx
    ON book_loans (book_id)
    WHERE returned_at IS NULL;

CREATE INDEX book_loans_member_idx
    ON book_loans (member_id, issued_at DESC);

CREATE TABLE visit_slots (
    slot_id SMALLINT PRIMARY KEY,
    label TEXT NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    sort_order SMALLINT NOT NULL,
    CONSTRAINT visit_slots_label_not_blank CHECK (BTRIM(label) <> ''),
    CONSTRAINT visit_slots_time_window_check CHECK (end_time > start_time),
    CONSTRAINT visit_slots_sort_order_check CHECK (sort_order > 0)
);

INSERT INTO visit_slots (slot_id, label, start_time, end_time, sort_order)
VALUES
    (1, '09:00 - 11:00', TIME '09:00', TIME '11:00', 1),
    (2, '11:00 - 13:00', TIME '11:00', TIME '13:00', 2),
    (3, '14:00 - 16:00', TIME '14:00', TIME '16:00', 3),
    (4, '16:00 - 18:00', TIME '16:00', TIME '18:00', 4);

CREATE TABLE slot_bookings (
    slot_booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    book_id BIGINT NOT NULL REFERENCES books(book_id) ON DELETE RESTRICT,
    slot_id SMALLINT NOT NULL REFERENCES visit_slots(slot_id) ON DELETE RESTRICT,
    slot_date DATE NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    reviewed_at TIMESTAMPTZ,
    reviewed_by_user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    rejection_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    cancelled_at TIMESTAMPTZ,
    fulfilled_at TIMESTAMPTZ,
    CONSTRAINT slot_bookings_status_check CHECK (
        status IN ('pending', 'approved', 'rejected', 'cancelled', 'fulfilled', 'expired')
    ),
    CONSTRAINT slot_bookings_cancelled_at_check CHECK (
        (status = 'cancelled' AND cancelled_at IS NOT NULL)
        OR status <> 'cancelled'
    ),
    CONSTRAINT slot_bookings_fulfilled_at_check CHECK (
        (status = 'fulfilled' AND fulfilled_at IS NOT NULL)
        OR status <> 'fulfilled'
    ),
    CONSTRAINT slot_bookings_review_fields_check CHECK (
        (status = 'pending' AND reviewed_at IS NULL AND reviewed_by_user_id IS NULL AND rejection_reason IS NULL)
        OR (status = 'approved' AND reviewed_at IS NOT NULL AND reviewed_by_user_id IS NOT NULL AND rejection_reason IS NULL)
        OR (status = 'rejected' AND reviewed_at IS NOT NULL AND reviewed_by_user_id IS NOT NULL AND rejection_reason IS NOT NULL)
        OR (status NOT IN ('pending', 'approved', 'rejected'))
    ),
    CONSTRAINT slot_bookings_rejection_reason_check CHECK (
        (status = 'rejected' AND rejection_reason IS NOT NULL)
        OR status <> 'rejected'
    )
);

CREATE UNIQUE INDEX slot_bookings_one_active_per_member_book_uidx
    ON slot_bookings (member_id, book_id)
    WHERE status IN ('pending', 'approved');

CREATE INDEX slot_bookings_active_capacity_idx
    ON slot_bookings (book_id, slot_date)
    WHERE status IN ('pending', 'approved');

CREATE INDEX slot_bookings_member_idx
    ON slot_bookings (member_id, slot_date DESC);

CREATE TABLE waitlist_entries (
    waitlist_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    book_id BIGINT NOT NULL REFERENCES books(book_id) ON DELETE RESTRICT,
    status TEXT NOT NULL DEFAULT 'waiting',
    position INTEGER,
    notified_at TIMESTAMPTZ,
    fulfilled_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT waitlist_entries_status_check CHECK (
        status IN ('waiting', 'notified', 'fulfilled', 'cancelled')
    ),
    CONSTRAINT waitlist_entries_position_check CHECK (
        position IS NULL OR position > 0
    ),
    CONSTRAINT waitlist_entries_notified_at_check CHECK (
        (status IN ('notified', 'fulfilled') AND notified_at IS NOT NULL)
        OR status NOT IN ('notified', 'fulfilled')
    ),
    CONSTRAINT waitlist_entries_fulfilled_at_check CHECK (
        (status = 'fulfilled' AND fulfilled_at IS NOT NULL)
        OR status <> 'fulfilled'
    ),
    CONSTRAINT waitlist_entries_cancelled_at_check CHECK (
        (status = 'cancelled' AND cancelled_at IS NOT NULL)
        OR status <> 'cancelled'
    )
);

CREATE UNIQUE INDEX waitlist_entries_one_waiting_per_member_book_uidx
    ON waitlist_entries (member_id, book_id)
    WHERE status = 'waiting';

CREATE INDEX waitlist_entries_book_status_created_idx
    ON waitlist_entries (book_id, status, created_at);

CREATE INDEX waitlist_entries_member_idx
    ON waitlist_entries (member_id, created_at DESC);

CREATE TABLE favorite_books (
    favorite_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    book_id BIGINT NOT NULL REFERENCES books(book_id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT favorite_books_unique_member_book UNIQUE (member_id, book_id)
);

CREATE INDEX favorite_books_member_idx
    ON favorite_books (member_id, created_at DESC);

CREATE INDEX favorite_books_book_idx
    ON favorite_books (book_id, created_at DESC);

CREATE TABLE book_reviews (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    book_id BIGINT NOT NULL REFERENCES books(book_id) ON DELETE CASCADE,
    rating SMALLINT NOT NULL,
    review_text TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT book_reviews_rating_check CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT book_reviews_unique_member_book UNIQUE (member_id, book_id)
);

CREATE INDEX book_reviews_book_idx
    ON book_reviews (book_id, updated_at DESC);

CREATE INDEX book_reviews_member_idx
    ON book_reviews (member_id, updated_at DESC);

CREATE TABLE notifications (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    category TEXT NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    link_path TEXT,
    book_id BIGINT REFERENCES books(book_id) ON DELETE SET NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT notifications_category_not_blank CHECK (BTRIM(category) <> ''),
    CONSTRAINT notifications_title_not_blank CHECK (BTRIM(title) <> ''),
    CONSTRAINT notifications_message_not_blank CHECK (BTRIM(message) <> ''),
    CONSTRAINT notifications_read_state_check CHECK (
        (is_read = FALSE AND read_at IS NULL)
        OR (is_read = TRUE AND read_at IS NOT NULL)
    )
);

CREATE INDEX notifications_user_created_idx
    ON notifications (user_id, created_at DESC);

CREATE INDEX notifications_user_unread_idx
    ON notifications (user_id, is_read, created_at DESC);

CREATE TABLE email_otps (
    email_otp_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    purpose TEXT NOT NULL,
    otp_hash TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT email_otps_purpose_check CHECK (
        purpose IN ('email_verification', 'password_reset')
    ),
    CONSTRAINT email_otps_email_not_blank CHECK (BTRIM(email) <> ''),
    CONSTRAINT email_otps_hash_not_blank CHECK (BTRIM(otp_hash) <> ''),
    CONSTRAINT email_otps_expires_after_create_check CHECK (
        expires_at > created_at
    ),
    CONSTRAINT email_otps_consumed_after_create_check CHECK (
        consumed_at IS NULL OR consumed_at >= created_at
    )
);

CREATE INDEX email_otps_email_purpose_idx
    ON email_otps ((LOWER(email)), purpose, created_at DESC);

CREATE INDEX email_otps_user_idx
    ON email_otps (user_id, created_at DESC)
    WHERE user_id IS NOT NULL;

CREATE TRIGGER libraries_set_updated_at
    BEFORE UPDATE ON libraries
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER users_set_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER books_set_updated_at
    BEFORE UPDATE ON books
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER borrow_requests_set_updated_at
    BEFORE UPDATE ON borrow_requests
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER book_loans_set_updated_at
    BEFORE UPDATE ON book_loans
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER slot_bookings_set_updated_at
    BEFORE UPDATE ON slot_bookings
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER waitlist_entries_set_updated_at
    BEFORE UPDATE ON waitlist_entries
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER book_reviews_set_updated_at
    BEFORE UPDATE ON book_reviews
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER notifications_set_updated_at
    BEFORE UPDATE ON notifications
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMIT;
